AllCops:
  TargetRubyVersion: 2.4
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

TrailingBlankLines:
  Enabled: true

Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'test/**/*.rb'

Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'
    - 'config/routes.rb'

Metrics/LineLength:
  Max: 120

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_auth_hash

Style/ClassAndModuleChildren:
  Enabled: false
