language: ruby

rvm:
  - 2.4.0

sudo: false

before_install:
  - gem update --system

before_script:
  - psql -c 'create database classroom_test;' -U postgres

script:
  - bundle exec rails test

bundler_args: --without development production --deployment --jobs=3 --retry=3

cache: bundler

services:
  - postgresql
  - redis-server

env:
  global:
    - CLASSROOM_WEBHOOK_URL_PREFIX="https://example.com/github/hooks"
    - GITHUB_CLIENT_ID="client_id"
    - GITHUB_CLIENT_SECRET="client_secret"
    - TEST_CLASSROOM_TEACHER_GITHUB_ID=1
    - TEST_CLASSROOM_TEACHER_GITHUB_TOKEN=2
    - TEST_CLASSROOM_STUDENT_GITHUB_ID=3
    - TEST_CLASSROOM_STUDENT_GITHUB_TOKEN=4
    - TEST_CLASSROOM_ORGANIZATION_GITHUB_ID=5
    - TEST_CLASSROOM_ORGANIZATION_GITHUB_LOGIN="the-classroom"
    - WEBHOOK_SECRET="abcdefg"

notifications:
  email: false
